GreepTheSheep/openplanet-MXRandom

src/Methods.as

This change limits the search of random maps on TM2020 in order to prevent loading shootmania-style "CharacterPilot" maps. That scenario usually leads to run-ending crashes, so its better to just filter them out.
It seems like this filter excludes about 30 maps from TMX total. You can't search for them directly (vehicles=-1 filter doesn't work), but this is the difference in numbers of maps between search with and without the filter applied.
Example of such map: https://trackmania.exchange/maps/1716/cactus
Here is a world record run that got ended because of this: https://www.twitch.tv/videos/1157699620 The crash happens in last couple of minutes of the stream.

prevent loading shootmania maps

---

src/TimerUI.as

Fix timer reseting to 2mins when skip is done with less than 2mins remaining when playing Survival mode

fix: Timer Skip Survival

---

src/Utils/RMC/RMCConfigs.as

This fixes prepatch warnings showing on every ice map regardless of the map's exe build.

Fixed prepatch warnings always showing regardless of exe build

---

src/Interface/ModalDialogs/DataMigrationWizardModalDialog.as
src/Interface/ModalDialogs/Modes/ChaosIntroduction.as
src/Interface/ModalDialogs/Modes/RMTHelpModalDialog.as
src/Interface/ModalDialogs/SurvivalFreeSkipWarnModalDialog.as
src/Interface/Views/MainUI.as

This adds support for UI scaling introduced in Openplanet 1.25.40.
Main UI at 125%:
Free skip dialog at 125%:
(And a bunch of other fixes in other dialogs.)

Scaling fixes

---

src/Settings/SearchingParameters.as
src/Utils/MX/Methods/LoadRandomMap.as
src/Utils/RMC/GlobalProperties.as

This allows you to disable the usage of length query parameters in API requests. This offers a partial fix for #68.
Ideally this also completely fixes the timeout issues, but I'm not sure if making query parameters opt-in immediately is the best thing to do.

fix: remove length parameters

---

src/Settings/SearchingParameters.as
src/Utils/MX/Methods/LoadRandomMap.as

This allows you to set filters on map pack, map name or map author(s). 
This is inspired by the mapper of the fab lol maps, who wants to have an RMC-like competition on his maps as he reached over 1000 maps by now.

feat: allow map name/map pack/map author filtering for maps

---

src/Utils/RMC/GlobalProperties.as

This is necessary as a map could have been preloaded from a previous run with custom parameters. If you start a leaderboard run after and a map with custom parameters still is preloaded the run would be invalid. So it is best to load new maps on every newly started run.

fix: remove preloaded map on new challenge start

---

src/Settings/SearchingParameters.as
src/Utils/RMC/RMC.as

This displays the invalidity of a run clearer, when custom parameters are enabled.

refactor(UI): put stronger emphasis on the invalidity of a run

---

src/Exports/ExportsCode.as
src/Interface/Renders/RecentlyMapsList.as
src/Settings/About.as
src/Settings/RMCParameters.as
src/Utils/MX/Methods/DownloadMap.as
src/Utils/MX/Methods/FetchMapTags.as
src/Utils/MX/Methods/LoadRandomMap.as
src/Utils/Migration.as

This will make it possible to run tests against a local simulator/mock for the MX api, but additionally make it so users of the plugin can stand up their own proxy api server to serve preloaded and cached api response data from the MX api. This will allow users to be not as dependent on the uptime and reliability of the MX api when doing RMC/S runs.
I debated putting this under the search settings, but since those seemed to be opting into a custom ruleset that additionally invalidates being on the official leaderboard, this didnt really seem like a great fit. Ofc, allowing ANY proxies to be included here, does mean someone could circumvent "randomness" by mocking responses for maps they are already familiar with OR find easier looking maps to essentially cheat official leaderboards... so …

Add ability to proxy trackmania api to another url

---

src/Settings/SearchingParameters.as
src/Utils/MX/Methods/LoadRandomMap.as

The TMX API only checks if the author name specified in the request is *in* the map so this adds a setting that ensures the specified author matches the map author exactly.

feat: check for exact map author

---

src/Utils/RMC/RMT.as

Additionally add a try {} catch {} so recovery is possible if an exception is thrown.
Should fix #89 
Note: made PR from github so please confirm this compiles.
The only substantial change (besides try catch) is this line: `if (player.BestRaceTimes is null || player.BestRaceTimes.Length != raceData.CPsToFinish) continue;`

Fix null pointer exception with player best times

---

src/Utils/NadeoServices/Methods.as
src/Utils/RMC/RMT.as

I suspect that one of the reasons map changing is a little unreliable is because there's a race condition updating the server. Something like this:
- Request 1 is fired and received by nadeo (map list)
- Server processes update and sends an async msg to the game server to update settings / download map / etc
- Server returns status 200
- Request 2 is fired and received (update timer)
- At this point, the game server hasn't been updated -- maybe the map is still downloading
- Server constructs update payload that ends up using old cached info / map list, sends async msg to game server
- Game server gets the update timer payload, and then either ignores the map update or the map update gets overriden by the update timer. 
An alternate solution would be to watch the list of maps and wait for …

RMT: Update room with 1 request not 2, fix race condition while changing maps

---

src/Utils/DataManager.as
src/Utils/MX/Methods/LoadRandomMap.as
src/Utils/RMC/GlobalProperties.as

This removes the forced TMX API request by saving a copy of the relevant map data when saving, so that you can load runs even when TMX is completely down.
Note: as saving runs is an unreleased change there is no need to check for the old "mapID" key.

fix: dont rely on tmx when loading a save

---

src/Constants.as
src/Utils/Game/Methods.as
src/Utils/MX/Methods/LoadRandomMap.as

Title! Currently, both this and the ManiaExchange menu are a bit odd in their behavior in MP4. Notably, when launching a map, you're immediately faced with MP3's UI, among other oddities. This is because the plugin isn't loading any gamemode at all, instead relying on the engine's fallback gamemode.
So this PR is incredibly straight-forward: it makes the plugin's maploading load the gamemode that Nadeo's maniascript generally tries to enforce as a default, that gamemode being `SingleMap`. This applies only for MP4, and leaves TM2020 untouched (in theory at least; we can't test that for certain)
This makes loading a map through the plugin behave exactly as a map loaded through the game's menus would behave, as one would naturally expect a plugin like this to achieve.

Makes MP4 use the SingleMap gamemode instead of the engine fallback

---

src/Interface/ModalDialogs/SaveRunQuestionModalDialog.as
src/Utils/DataManager.as
src/Utils/RMC/GlobalProperties.as
src/Utils/RMC/RMC.as
src/Utils/RMC/RMS.as

fixes issues regarding autosaves and combines autosaves and normal saves into one function.
fixed:
- issue where the autosave value for "timer remaining" would always be 0 ``(-1 - (-1))`` because of the wrong variable used. This renders autosaves unusable (the save is created, but not considered as the remaining time is 0). 
- issue where a broken map could save as the last played map in the autosave, making the run unusable as the save file destroys when the run is loaded but the game crashes again due to the map being broken
changed:
- combined save & autosave into one function as only one variable differs.
- Autosaves now happen on every PB instead of when the map changes.
A quick new release for this would be appreciated, as currently runs are not continuable if the game crashes, [see …

refactor: improve (auto)saving system

---

src/Interface/ModalDialogs/BrokenMapSkipWarnModalDialog.as
src/Settings/RMCParameters.as
src/Utils/DataManager.as
src/Utils/RMC/GlobalProperties.as
src/Utils/RMC/ObjectiveMode.as
src/Utils/RMC/RMC.as
src/Utils/RMC/RMS.as
src/Utils/RMC/RMT.as

fixes #100 
This changes the skip buttons to be more clear in their purpose and to always return the time if the map is broken.

refactor: imrpove Skip Buttons for RMC and RMS

---

src/Utils/DataManager.as

resolves #115 .
This is not a fix for the underlying issue if one exists. I have not found a way to reproduce corrupted save files without modifying files manually, so it is not likely to occur under normal circumstances (otherwise there'd be a lot more people complaining). If it still occurs, this will remove the corrupt file and start a new run.

fix: prevent skript exceptions when save files are corrupted

---

src/Settings/SearchingParameters.as
src/Utils/RMC/RMT.as

There are times where maps are reused, expecially when providing a custom mappack. This caches the TrackUID in a dictionary and skips any already seen maps.
Tested with a mappack that has a single map in it: https://trackmania.exchange/mappack/view/3745

Skip seen maps when fetching next RMT map

---

src/Utils/RMC/RMT.as

this uses MLFeed to provide a current status of each players current run in the RMT session. This can be used to avoid skipping when a player is on a banger run. 
(Note: apologies, some of these screenshots are of TMX together not RMT (I had both running) but I copy-pasted the code between them)
Information shown is: player name, current CP count, last CP time, delta to best time of that player this session. When a player finishes, their final time is shown in green or red depending on whether it was better or worse than their best time.
The asterisk indicates >= 1 cp behind.
The sorting method on players is time attack, so it will show players in order of their potential runs. The alternative is the race sorting method, where players with more CPs are near the top (so a slow player with …

add current runs to RMT

---

src/Utils/RMC/GlobalProperties.as

When using a free skip during a run, RMC::FreeSkipsUsed is increased by one
https://github.com/GreepTheSheep/openplanet-MXRandom/blob/85ce6d140b749f70540cac08ababde1c35dec863/src/Utils/RMC/RMC.as#L281
but this counter isn't reset between runs, so when comparing it to the free skip amount set by the user, it's counting the total amount of skips used since the plugin was loaded
https://github.com/GreepTheSheep/openplanet-MXRandom/blob/85ce6d140b749f70540cac08ababde1c35dec863/src/Utils/RMC/RMC.as#L273
Fixes #133

Fix free skips

---

src/Settings/SearchingParameters.as
src/Utils/Dates.as
src/Utils/MX/Methods/LoadRandomMap.as

fixes #128 
Adds new Searching parameter to allow filtering maps inside a date interval. This is useful to be able to play maps only before an important game patch or update, for example.
This setting is only used if CustomRules setting is also set to true, to prevent these runs getting into the official leaderboard.
Date parsing from a string is done using [this suggestion](https://github.com/MisfitMaid/tm-ticker/blob/d8758b5439317dd0fe8357408013f4731557986b/Helpers.as#L19) by @misfitmaid

Add date interval as searching parameter

---

src/Utils/RMC/RMC.as
src/Utils/RMC/RMT.as

Plugin stopped working on MP4 because it tries to check if the selected goal is WRs, but that medal is only included in TM2020
https://github.com/GreepTheSheep/openplanet-MXRandom/blob/55af5804ae91674d02b400b5988443b27ff8a941/src/Utils/RMC/GlobalProperties.as#L27-L35
This PR makes it so it only checks for that medal if the game is TMNEXT. Also simplifies the belowMedal check while fixing the issue
<details>
<summary>Proof of the plugin working</summary>
</details>
P.S.: Tried to fix the issue without touching/changing the code too much just in case, but let me know if you have a different idea to fix it
Fixes #129

Only check for WR medal on TMNEXT

---

src/Utils/RMC/GlobalProperties.as
src/Utils/RMC/ObjectiveMode.as
src/Utils/RMC/RMC.as

Once the plugin started working again for MP4, I was getting lags/freezes after playing for some minutes. Coincidentally, I noticed the log file was getting absurdly large, which ended up being the cause of the freezes 
This happens because, in dev mode, RMC::GetCurrentMapMedal prints the current medal stats almost every frame. This is caused due to multiple reasons:
* MP4 PB fetching only checked if there was a ghost, so it would repeatedly get the same time over and over again
* In the if statements for each mode, it would first get the current medal, and _then_ see if the player already had the medal. This is fixed by inverting the order of conditions
* For the below medal check, the if statement was only checking if the player already had the goal medal, but not the one below (so even …

Improve PB fetching to avoid log spam, fix autosaves

---

src/Settings/SearchingParameters.as
src/Utils/MX/Methods/FetchMapTags.as

This PR tries to partially address #102, since I also got confused about them before. The changes are mostly visual and don't affect functionality
* Make custom rules checkbox text generic, since they affect all game modes as far as I know.
* Disable all custom parameters if the custom rules checkbox isn't enabled. This should make it clear that you need to enable this setting to use them.
* Include tag count when there's any tag selected and sort them alphabetically
* Add tooltips for the tag inclusive and skip seen maps checkboxes
This PR also fixes the following issues:
* Minimum value for the year slider was 2020 for MP4 too
* Date interval table used the same name as the tags table. This would shrink the tags table when the date interval one was rendered
* Date intervals values …

Make custom parameters more intuitive, few fixes

---

src/Utils/RMC/GlobalProperties.as

Noticed this issue while watching a stream (notice how it's a fresh run but with an hour spent on the map)
VOD to see the issue: https://www.twitch.tv/videos/2311715689?t=00h06m45s

Fix timer for the first map in a fresh run

---

src/Constants.as
src/Exports/ExportsCode.as
src/Interface/ModalDialogs/DataMigrationWizardModalDialog.as
src/Interface/ModalDialogs/MX2MigrationWizardModalDialog.as
src/Interface/Renders/RecentlyMapsList.as
src/Main.as
src/Settings/About.as
src/Settings/AdvancedParameters.as
src/Settings/SearchingParameters.as
src/Utils/Dates.as
src/Utils/Logging.as
src/Utils/MX/Entities/MapInfo.as
src/Utils/MX/Entities/MapTag.as
src/Utils/MX/Methods/DownloadMap.as
src/Utils/MX/Methods/FetchMapTags.as
src/Utils/MX/Methods/LoadRandomMap.as
src/Utils/Migration.as
src/Utils/RMC/GlobalProperties.as
src/Utils/RMC/ObjectiveMode.as
src/Utils/RMC/RMC.as
src/Utils/RMC/RMT.as

Like with the ManiaExchange plugin, this PR migrates the plugin to MX 2.0. Functionality should be almost the same, besides some filters/options that don't exist on the new site
This also adds a modal dialog to migrate the already existing 1.0 data to 2.0. This is mainly based on the previous data migration process done by the plugin
I couldn't find any issues when testing on both TM2 and TMNEXT, but I highly recommend testing the changes if possible
P.S.: I also added a check for the new ServerSizeExceeded value. Fixes #140

Migrate to MX 2.0

---

src/Utils/RMC/RMC.as
src/Utils/RMC/RMS.as

- Fixes alignment of skip count text in RMS overlay
- Fixes AT (goal) medal count overlap with belowgoalmedalcount when it's too big (i.e > 100)
Before (note how the 0 skips is slightly unaligned upwards): 
After:

fix medal count alignment and overlaps
